### PR TITLE
fixed file location

### PR DESCRIPTION
**Pull request by anizeani**

### CODE REVIEW

**Comment by anizeani** [comment]
minor change, but I can't merge to master by myself @brenzi (authorization required)

**Review by clangenb — APPROVED** [review]
So the scripts assume to be run from the repository root dir?

**Comment by anizeani** [comment]
No, we refactored the test-data location into the client folder #126. The scripts are still run in the client folder. This is the change

**Comment by clangenb** [comment]
Ok, I see. Thanks for explaining. 👍

**Pull request merged**
