### PR TITLE
implement aggregated account data rpc

### PR DESCRIPTION
**Pull request by pifragile**

### CODE REVIEW

**Review by clangenb — APPROVED** [review]
LGTM, did you actually test that the rpc returns the correct value? An example of the returned result would be cool.

**Comment by brenzi** [comment]
what about the cli client? don't we need to adapt namings there?

...we need to: please scan the cöli client for rpc calls and rename there. it seems none of them are tested in CI as everything passed, but that's just our bad coverage

i.e.:
https://github.com/encointer/encointer-node/blob/dca45027de7dd60f6a49282efca2dd772462c537/client/src/main.rs#L1341-L1347

**Comment by clangenb** [comment]
This does only add an RPC, which has not been integrated in the CLI yet, but the RPCs from before they still work. I suggest doing this in a separate task. So we have it at least in the runtime, I'd just like to test it in polkadot-js/apps to see that it works.

**Comment by brenzi** [comment]
haha, ok, I was mislead. pardon. go ahead!

**Comment by clangenb** [comment]
I just tested that the rpc exists in the retrieved by polkadot-js/apps

**Pull request merged**
