### PR TITLE
collect ksm fees 18

### PR DESCRIPTION
**Pull request by NicJak**
please verify that the constants set are as intentioned by the task, as I am not proficient in this area.
I mapped the following:
"no block author reward. 100% to treasury" -> TREASURY_FUNDING_PERCENT
"no burn" -> pub const Burn: Permill = Permill::zero();

also: 
please propose the correct value for runtime/.../lib.rs:g317:
pub const ProposalBondMinimum: Balance = 1; //TODO add minimum balance

### CODE REVIEW

**Comment by NicJak** [comment]
ps: the changes in the lock files come from one of the issues when tackling this task: there were issues with the compatibility of the encointer-client-notee package that were resolved this way with the help of @clangenb

**Comment by brenzi** [comment]
what issue are you working on? Why do you add a treasury to the solochain?

**Comment by brenzi** [comment]
you're in the wrong repo mate ;-) @NicJak

**Comment by clangenb** [comment]
I did this in the parachain repo already ;).

So we can close this, and I don't need to review?

**Comment by NicJak** [comment]
yes, nevermind

**Pull request closed without merging**
