### PR TITLE
change RPC prefixes

### PR DESCRIPTION
**Pull request by pifragile**
Change RPC prefixes according to https://github.com/encointer/pallets/commit/dc863acf408e552dd7177881824c895856f1f516

### CODE REVIEW

**Comment by brenzi** [comment]
I guess you didn't downgrade substrate. You just reverted the accidental upgrade cargo did when bumping pallets, right?

**Comment by pifragile** [comment]
> I guess you didn't downgrade substrate. You just reverted the accidental upgrade cargo did when bumping pallets, right?

yes😅

**Review by clangenb — APPROVED** [review]
CI passes so ready to merge from my side.

I made an issue for updating the prefixes in https://github.com/encointer/encointer-js/issues/59

**Comment by clangenb** [comment]
@brenzi Do you want to wait, or can we merge this?

**Comment by brenzi** [comment]
We missed the window of opportunity to get it into the parachain runtime. If we can bend it to work with our para runtime with only updating the collator binary, fine, then we should move forward asap and align all interfaces including the mobile app and ci

**Comment by clangenb** [comment]
This does not touch the runtime, we should be able to update the collator without any problems.

**Pull request merged**
